python jobs.py \
    --job_name=siamese \
    --model_name=simplest \
    --source_path=../input/mars/bbox_train/ \
    --epochs=1000 \
    --num_per_class=2 \
    --loss=triplet_all \
    --metric=eucledian_squared \
    --margin=0.5 \
    --lr=1e-3 \
    --log_every=1 \
    --save_dir=./checkpoints \
    --save_every=500 \
    --validate_every=100 \
    --normalized=1 \
    --num_classes=2 \
    --batch_size=2
